### PR TITLE
make: Add patch that fixes comparation of glob interface versions

### PR DESCRIPTION
**Pull request by DmitriiKolesnichenko**

### CODE REVIEW

**Comment by anthony-kolesov** [comment]
Please add the link to the original patch and also error message that is being fixed by this patch.

**Comment by abrodkin** [comment]
As usual - what about upstream Buildroot? Was that patch ever sent there or are there any plans to do so?

**Comment by cupertinomiranda** [comment]
To my understanding this patch applies over gnu-make source code.
Does this patch need to be applied in buildroot or should buildroot
consider to update the version of gnu-make it is pointed to ?

Best regards,
Cupertino

**Comment by DmitriiKolesnichenko** [comment]
Code update didn't help because this patch was applied after latest release.

**Comment by abrodkin** [comment]
@DmitriiKolesnichenko Anyways I do think it worth sending to buildroot in one or another form so then this fix returns to us with the next Buildroot release.

**Comment by DmitriiKolesnichenko** [comment]
@abrodkin Okay, I will do it

**Pull request merged**
